name: Run Python Unit Tests on Multiple Platforms
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false  # 失敗後繼續運行
      matrix:
        os: [ubuntu-latest, windows-2019, windows-latest, macos-latest]
        python-version: ['3.10', '3.x']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies (Linux/Mac)
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Install rsync (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Invoke-WebRequest -Uri "https://itefix.net/download/free/cwrsync_6.3.1_x64_free.zip" -OutFile "rsync.zip"
        # Expand-Archive -Path "rsync.zip" -DestinationPath "rsync"
        # echo "${{ github.workspace }}\rsync\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "${{ github.workspace }}\.github\workflows\rsync\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) { python -m pip install -r requirements.txt }
      shell: pwsh

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p "*.py"